-- SELECT TRÊN BẢNG NHÂN VIÊN
    CREATE OR REPLACE PROCEDURE X_ADMIN_SELECT_NHANVIEN_TABLE_FOR_NVTCHC(
        p_result OUT SYS_REFCURSOR
    )
    AS
    BEGIN
        OPEN p_result FOR
        SELECT * FROM X_ADMIN.NHANVIEN;
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
            RAISE;
    END;
    /
    GRANT EXECUTE ON X_ADMIN_SELECT_NHANVIEN_TABLE_FOR_NVTCHC TO XR_NVTCHC;
-- UPDATE TRÊN BẢNG NHÂN VIÊN
    CREATE OR REPLACE PROCEDURE X_ADMIN_UPDATE_NHANVIEN_TABLE_FOR_NVTCHC (
        MaNLD    IN VARCHAR2,
        HoTen    IN VARCHAR2,
        PHAI     IN VARCHAR2,
        NgaySinh IN DATE,
        Luong    IN INTEGER,
        PhuCap   IN INTEGER,
        SDT      IN VARCHAR2,
        VaiTro   IN VARCHAR2,
        MaDV     IN VARCHAR2
    ) AS
    BEGIN
        UPDATE X_ADMIN.NHANVIEN
        SET
            HOTEN  = HoTen,
            PHAI   = PHAI,
            NGSINH = NgaySinh,
            LUONG  = Luong,
            PHUCAP = PhuCap,
            DT     = SDT,
            VAITRO = VaiTro,
            MADV   = MaDV
        WHERE MANV = MaNLD;
        
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
            RAISE;
    END;
    /
    GRANT EXECUTE ON X_ADMIN_UPDATE_NHANVIEN_TABLE_FOR_NVTCHC TO XR_NVTCHC;
-- DELETE TRÊN BẢNG NHÂN VIÊN
    CREATE OR REPLACE PROCEDURE X_ADMIN_DELETE_NHANVIEN_TABLE_FOR_NVTCHC(
        MaNLD IN VARCHAR2)
    AS 
    BEGIN
        EXECUTE IMMEDIATE 'DELETE FROM X_ADMIN.NHANVIEN WHERE MANV = ''' || MaNLD || '''';
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
            RAISE;
    END;
    /
    GRANT EXECUTE ON X_ADMIN_DELETE_NHANVIEN_TABLE_FOR_NVTCHC TO XR_NVTCHC;
-- INSERT TRÊN BẢNG NHÂN VIÊN
    CREATE OR REPLACE PROCEDURE X_ADMIN_INSERT_NHANVIEN_TABLE_FOR_NVTCHC(
        MaNLD IN VARCHAR2,
        HoTen IN VARCHAR2,
        PHAI IN VARCHAR2,
        NgaySinh IN DATE,
        Luong IN INTEGER,
        PhuCap IN INTEGER,
        SDT IN VARCHAR2,
        VaiTro IN VARCHAR2,
        MaDV IN VARCHAR2)
    AS
    BEGIN
        INSERT INTO X_ADMIN.NHANVIEN 
            (MANV, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MADV)
        VALUES (MaNLD, HoTen, PHAI, NgaySinh, Luong, PhuCap, SDT, VaiTro, MaDV); 
        EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
            RAISE;
    END;
    /
    GRANT EXECUTE ON X_ADMIN_INSERT_NHANVIEN_TABLE_FOR_NVTCHC TO XR_NVTCHC;

COMMIT;