-- Create admin user
CREATE USER X_ADMIN IDENTIFIED BY 123;
GRANT CONNECT TO X_ADMIN WITH ADMIN OPTION;
GRANT RESOURCE TO X_ADMIN WITH ADMIN OPTION;
GRANT CREATE USER, ALTER USER, DROP USER TO X_ADMIN;
GRANT CREATE SESSION TO X_ADMIN WITH ADMIN OPTION;
GRANT SELECT ANY DICTIONARY TO X_ADMIN;

GRANT CREATE ROLE TO X_ADMIN;
GRANT GRANT ANY PRIVILEGE TO X_ADMIN;
GRANT CREATE SESSION TO X_ADMIN;
GRANT CREATE ANY CONTEXT TO X_ADMIN;
GRANT ADMINISTER DATABASE TRIGGER TO X_ADMIN;
GRANT CREATE ANY VIEW TO X_ADMIN;
GRANT EXECUTE ON DBMS_RLS TO X_ADMIN;
GRANT CREATE VIEW TO X_ADMIN;
GRANT CREATE TRIGGER TO X_ADMIN;
GRANT DBA TO X_ADMIN;

ALTER USER X_ADMIN QUOTA UNLIMITED ON USERS;

COMMIT;

