SHOW CON_NAME;

-- Create admin user
CREATE USER X_ADMIN IDENTIFIED BY 123;
GRANT CONNECT TO X_ADMIN;
GRANT RESOURCE TO X_ADMIN;
GRANT CREATE USER, ALTER USER, DROP USER TO X_ADMIN;
GRANT CREATE SESSION TO X_ADMIN WITH ADMIN OPTION;
GRANT SELECT ON DBA_ROLE_PRIVS TO X_ADMIN;

-- Create role NVCB
CREATE ROLE NVCB;
-- Create role GV
CREATE ROLE GV;
-- Create role NVPDT
CREATE ROLE NVPDT;
-- Create role NVPKT
CREATE ROLE NVPKT;
-- Create role NVTCHC
CREATE ROLE NVTCHC;
-- Create role NVCTV
CREATE ROLE NVCSTV;
-- Create role TRGDV
CREATE ROLE TRGDV;
-- Create role SINHVIEN
CREATE ROLE SV;
GRANT CREATE SESSION TO SV;
/
-- Create dba
-- ALTER SESSION SET CONTAINER = CDB$ROOT;
-- CREATE USER C##ADMIN1 IDENTIFIED BY pqkiet854;  
-- GRANT DBA TO C##ADMIN1; 
-- GRANT EXECUTE ANY PROCEDURE TO C##ADMIN1;
-- GRANT CREATE SESSION TO C##ADMIN1 CONTAINER = ALL;

-- Create users with role SINHVIEN
CREATE USER SV001 IDENTIFIED BY pqkiet854;
GRANT SV TO SV001;

COMMIT;


-- DROP users and roles
DROP ROLE GV;
DROP ROLE NVCB;
DROP ROLE NVPDT;
DROP ROLE NVPKT;
DROP ROLE NVTCHC;
DROP ROLE NVCSTV;
DROP ROLE TRGDV;
DROP ROLE SV;
