SELECT * FROM X_ADMIN.USER_ROLES;
SELECT * from X_ADMIN.SINHVIEN;
SELECT * from X_ADMIN.DANGKY;
SELECT * from X_ADMIN.MOMON;
SELECT * from X_ADMIN.HOCPHAN;
SELECT * from X_ADMIN.NHANVIEN;
SELECT * FROM X_ADMIN.DONVI;
SELECT * FROm X_ADMIN.VIEW_NVCB_NV;

DECLARE
   username VARCHAR2(10);
    isSV INTEGER;
    isNVCB INTEGER;
BEGIN
   username := SYS_CONTEXT('X_UNIVERITY_CONTEXT','USER_NAME');
   isSV := SYS_CONTEXT('X_UNIVERITY_CONTEXT','IS_SV');
   isNVCB := SYS_CONTEXT('X_UNIVERITY_CONTEXT','IS_NVCB');
   DBMS_OUTPUT.PUT_LINE('username: ' || username);
   DBMS_OUTPUT.PUT_LINE('isSV: ' || isSV);
   DBMS_OUTPUT.PUT_LINE('isNVCB: ' || isNVCB);
END;

COMMIT;