SELECT * FROM X_ADMIN.USER_ROLES;
SELECT * from X_ADMIN.SINHVIEN;
SELECT * from X_ADMIN.DANGKY;
SELECT * from X_ADMIN.MOMON;
SELECT * from X_ADMIN.HOCPHAN;
SELECT * from X_ADMIN.NHANVIEN;
SELECT * FROM X_ADMIN.DONVI;
SELECT * FROm X_ADMIN.VIEW_NVCB_NV;
DELETE FROM X_ADMIN.USER_ROLES WHERE USERNAME = 'NV0022';
DELETE FROM X_ADMIN.NHANVIEN WHERE MANV = 'NV0022';
DECLARE
   username VARCHAR2(10);
    isSV INTEGER;
    isNVCB INTEGER;
BEGIN
   username := SYS_CONTEXT('X_UNIVERITY_CONTEXT','USER_NAME');
   isSV := SYS_CONTEXT('X_UNIVERITY_CONTEXT','IS_SV');
   isNVCB := SYS_CONTEXT('X_UNIVERITY_CONTEXT','IS_NVCB');
   DBMS_OUTPUT.PUT_LINE('username: ' || username);
   DBMS_OUTPUT.PUT_LINE('isSV: ' || isSV);
   DBMS_OUTPUT.PUT_LINE('isNVCB: ' || isNVCB);
END;

SELECT MaMM 
       FROM X_ADMIN.MOMON
       WHERE CURRENT_DATE - TRUNC(TO_DATE(NAM || '-' || 
          CASE HK WHEN 1 THEN '09' WHEN 2 THEN '01' WHEN 3 THEN '05' END, 'YYYY-MM')) 
          BETWEEN 0 AND 13;
      
COMMIT;