SELECT * FROM X_ADMIN.USER_ROLES;
SELECT * from X_ADMIN.SINHVIEN;
SELECT * from X_ADMIN.DANGKY;
SELECT * from X_ADMIN.MOMON;
SELECT * from X_ADMIN.HOCPHAN;
SELECT * from X_ADMIN.NHANVIEN;
SELECT * FROM X_ADMIN.DONVI;