CREATE TABLE X_ADMIN.USER_ROLES(
    USERNAME VARCHAR2(10),
    ROLENAME VARCHAR2(10)
);

BEGIN
  FOR i IN (SELECT MASV FROM X_ADMIN.SINHVIEN) LOOP
    INSERT INTO X_ADMIN.USER_ROLES (USERNAME, ROLENAME) VALUES (i.MASV, 'XR_'|| 'SV');
  END LOOP;
END;
/
BEGIN
  FOR i IN (SELECT MANV, VAITRO FROM X_ADMIN.NHANVIEN) LOOP
    INSERT INTO X_ADMIN.USER_ROLES (USERNAME, ROLENAME) VALUES (i.MANV, 'XR_' || i.VAITRO);
  END LOOP;
END;
/

GRANT SELECT ON X_ADMIN.USER_ROLES TO PUBLIC;
COMMIT;

CREATE CONTEXT X_UNIVERITY_CONTEXT USING SET_X_UNIVERITY_CONTEXT;

CREATE OR REPLACE PROCEDURE SET_X_UNIVERITY_CONTEXT
AS
    isSV INTEGER;
    isGV INTEGER;
    isNVCB INTEGER;
    isNVPDT INTEGER;
    isNVPKT INTEGER;
    isNVTCHC INTEGER;
    isNVCTSV INTEGER;
    isTRGDV INTEGER;
BEGIN
    DBMS_SESSION.SET_CONTEXT('X_UNIVERITY_CONTEXT', 'USER_NAME', SYS_CONTEXT('USERENV', 'SESSION_USER'));

    SELECT COUNT(*) INTO isSV FROM SESSION_ROLES WHERE ROLE = 'XR_SV';
    DBMS_SESSION.SET_CONTEXT('X_UNIVERITY_CONTEXT', 'IS_SV', isSV);

    SELECT COUNT(*) INTO isGV FROM SESSION_ROLES WHERE ROLE = 'XR_GV';
    DBMS_SESSION.SET_CONTEXT('X_UNIVERITY_CONTEXT', 'IS_GV', isGV);

    SELECT COUNT(*) INTO isNVCB FROM SESSION_ROLES WHERE ROLE = 'XR_NVCB';
    DBMS_SESSION.SET_CONTEXT('X_UNIVERITY_CONTEXT', 'IS_NVCB', isNVCB);

    SELECT COUNT(*) INTO isNVPDT FROM SESSION_ROLES WHERE ROLE = 'XR_NVPDT';
    DBMS_SESSION.SET_CONTEXT('X_UNIVERITY_CONTEXT', 'IS_NVPDT', isNVPDT);

    SELECT COUNT(*) INTO isNVPKT FROM SESSION_ROLES WHERE ROLE = 'XR_NVPKT';
    DBMS_SESSION.SET_CONTEXT('X_UNIVERITY_CONTEXT', 'IS_NVPKT', isNVPKT);

    SELECT COUNT(*) INTO isNVTCHC FROM SESSION_ROLES WHERE ROLE = 'XR_NVTCHC';
    DBMS_SESSION.SET_CONTEXT('X_UNIVERITY_CONTEXT', 'IS_NVTCHC', isNVTCHC);

    SELECT COUNT(*) INTO isNVCTSV FROM SESSION_ROLES WHERE ROLE = 'XR_NVCTSV';
    DBMS_SESSION.SET_CONTEXT('X_UNIVERITY_CONTEXT', 'IS_NVCTSV', isNVCTSV);

    SELECT COUNT(*) INTO isTRGDV FROM SESSION_ROLES WHERE ROLE = 'XR_TRGDV';
    DBMS_SESSION.SET_CONTEXT('X_UNIVERITY_CONTEXT', 'IS_TRGDV', isTRGDV);
END;
/

GRANT EXECUTE ON SET_X_UNIVERITY_CONTEXT TO PUBLIC;

CREATE OR REPLACE TRIGGER SET_X_UNIVERITY_CONTEXT_TRIGGER
  AFTER LOGON ON DATABASE
BEGIN
  SET_X_UNIVERITY_CONTEXT;
END;
/
--DROP PROCEDURE SET_X_UNIVERITY_CONTEXT;
--DROP TRIGGER SET_X_UNIVERITY_CONTEXT_TRIGGER;
COMMIT;