CREATE TABLESPACE BACKUP_RECOVERY_TEST DATAFILE 'C:\AppStorage\oracle-db\oradata\XE\XEPDB1\BACKUP_RECOVERY_TEST.DBF'
SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

ALTER USER X_ADMIN QUOTA UNLIMITED ON BACKUP_RECOVERY_TEST;

CREATE TABLE DATA_TEST
(
    ID NUMBER,
    NAME VARCHAR2(50),
    AGE NUMBER
) TABLESPACE BACKUP_RECOVERY_TEST;

INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (1, 'John Doe', 30);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (2, 'Jane Smith', 25);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (3, 'Alice Johnson', 28);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (4, 'Bob Brown', 35);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (5, 'Charlie Davis', 22);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (6, 'Diana Evans', 27);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (7, 'Ethan Foster', 31);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (8, 'Fiona Green', 29);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (9, 'George Harris', 33);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (10, 'Hannah Ivers', 26);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (11, 'Ian Johnson', 24);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (12, 'Jack King', 32);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (13, 'Kathy Lee', 30);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (14, 'Liam Miller', 28);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (15, 'Mia Nelson', 27);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (16, 'Noah OBrien', 29);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (17, 'Olivia Parker', 31);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (18, 'Paul Quinn', 25);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (19, 'Quinn Roberts', 34);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (20, 'Rachel Smith', 23);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (21, 'Sam Taylor', 36);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (22, 'Tina Underwood', 30);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (23, 'Ursula Vance', 28);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (24, 'Victor White', 27);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (25, 'Wendy Xu', 29);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (26, 'Xander Young', 31);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (27, 'Yara Zhang', 25);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (28, 'Zoe Adams', 34);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (29, 'Aaron Brown', 23);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (30, 'Bella Clark', 36);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (31, 'Carter Davis', 30);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (32, 'Daisy Evans', 28);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (33, 'Eli Foster', 27);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (34, 'Felicity Green', 29);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (35, 'Gavin Harris', 31);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (36, 'Holly Ivers', 25);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (37, 'Isaac Johnson', 24);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (38, 'Julia King', 32);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (39, 'Kevin Lee', 30);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (40, 'Laura Miller', 28);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (41, 'Michael Nelson', 27);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (42, 'Nina OBrien', 29);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (43, 'Oliver Parker', 31);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (44, 'Paige Quinn', 25);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (45, 'Quincy Roberts', 34);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (46, 'Riley Smith', 23);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (47, 'Sophie Taylor', 36);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (48, 'Tyler Underwood', 30);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (49, 'Uma Vance', 28);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (50, 'Victor White', 27);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (51, 'Wendy Xu', 29);
INSERT INTO DATA_TEST (ID, NAME, AGE) VALUES (52, 'Xander Young', 31);

COMMIT;