-- Tạo view chỉ xem được thông tin của chính bản thân cho NVCB
<<<<<<< HEAD
CREATE OR REPLACE VIEW view_NVCB_NV AS 
SELECT * FROM NHANVIEN where MaNV = SUBSTR(SYS_CONTEXT('USERENV', 'SESSION_USER'), 3);

-- Gán quyền SELECT, UPDATE(DT) trên view_NVCB cho NVCB và gán role NVCB cho tất cả các vai trò khác
 GRANT SELECT, UPDATE(DT) ON X_ADMIN.view_NVCB_NV TO XR_NVCB;
 GRANT XR_NVCB TO XR_TRGDV, XR_NVTCHC, XR_GV, XR_NVPDT, XR_NVPKT, XR_NVCTSV;
=======
    CREATE OR REPLACE VIEW view_NVCB_NV AS 
    SELECT * FROM NHANVIEN where MaNV = SYS_CONTEXT('X_UNIVERITY_CONTEXT','USER_NAME');
    -- Gán quyền SELECT, UPDATE(DT) trên view_NVCB cho NVCB và gán role NVCB cho tất cả các vai trò khác
    GRANT SELECT, UPDATE(DT) ON X_ADMIN.view_NVCB_NV TO XR_NVCB;
    GRANT XR_NVCB TO XR_TRGDV, XR_NVTCHC, XR_GV, XR_NVPDT, XR_NVPKT, XR_NVCTSV;

>>>>>>> 4faf2d14a50582d7d7e1fc5157e1e224208108d8

-- Tạo view quản lý nhân viên cho trưởng đơn vị và cấp quyền SELECT trên view này cho TRGDV
    CREATE OR REPLACE VIEW view_TRGDV_NV AS 
    SELECT MANV, HOTEN, PHAI, NGSINH, DT, VAITRO, MADV
    FROM NHANVIEN 
    WHERE MADV = (SELECT MADV FROM NHANVIEN WHERE MANV = SYS_CONTEXT('X_UNIVERITY_CONTEXT','USER_NAME'));
    GRANT SELECT ON view_TRGDV_NV TO XR_TRGDV;
    -- Cấp toàn quyền trên bảng NHANVIEN cho NVTCHC
    GRANT SELECT, UPDATE, INSERT, DELETE ON NHANVIEN TO XR_NVTCHC;

COMMIT;
