DROP TABLE X_ADMIN.DANGKY;
DROP TABLE X_ADMIN.MOMON;
DROP TABLE X_ADMIN.SINHVIEN;
DROP TABLE HOCPHAN;

ALTER TABLE X_ADMIN.NHANVIEN DROP CONSTRAINT FK_NHANVIEN_DONVI;
DROP TABLE X_ADMIN.DONVI;
DROP TABLE X_ADMIN.NHANVIEN;