DROP TABLE X_ADMIN.DANGKY;
DROP TABLE X_ADMIN.MOMON;
DROP TABLE X_ADMIN.SINHVIEN;
DROP TABLE X_ADMIN.HOCPHAN;
DROP TABLE X_ADMIN.USER_ROLES;
DROP TABLE X_ADMIN.THONGBAO;
ALTER TABLE X_ADMIN.NHANVIEN DROP CONSTRAINT FK_NHANVIEN_DONVI;
ALTER TABLE X_ADMIN.DONVI DROP CONSTRAINT FK_TRUONGDONVI;
DROP TABLE X_ADMIN.DONVI;
DROP TABLE X_ADMIN.NHANVIEN;


DROP CONTEXT X_UNIVERSITY_CONTEXT;

DROP ROLE XR_NVCTSV;
DROP ROLE XR_NVTCHC;
DROP ROLE XR_NVPKT;
DROP ROLE XR_NVPDT;
DROP ROLE XR_NVCB;
DROP ROLE XR_GV;
DROP ROLE XR_TRGDV;
DROP ROLE XR_SV;

BEGIN
  FOR i IN (SELECT MASV FROM X_ADMIN.SINHVIEN) LOOP
    X_ADMIN.X_ADMIN_deleteUser('X_' || i.MASV);
  END LOOP;
END;
/
BEGIN
  FOR i IN (SELECT MANV, VAITRO FROM X_ADMIN.NHANVIEN) LOOP
    X_ADMIN.X_ADMIN_deleteUser('X_' || i.MANV);
  END LOOP;
END;
/

DROP USER X_ADMIN CASCADE;
-- BEGIN
--     SA_SYSDBA.DROP_POLICY('NOTIFICATION_POLICY');
-- END;
-- /
COMMIT;