CONNECT x_admin/123@localhost:1521/XEPDB1;
BEGIN
  FOR i IN (SELECT * FROM X_ADMIN.SINHVIEN) LOOP
    IF i.khoa = 'CNTT' THEN
        CONTINUE;
    END IF;
    X_ADMIN.X_ADMIN_CREATEUSER('X_' || i.MASV, '123','SINHVIEN');
    X_ADMIN.X_ADMIN_GRANTROLE('XR_SV', 'X_' || i.MASV, 'NO');
    
  END LOOP;
END;
/
BEGIN
  FOR i IN (SELECT * FROM X_ADMIN.NHANVIEN) LOOP
    IF i.madv = 'CNTT' THEN
        CONTINUE;
    END IF;
    X_ADMIN.X_ADMIN_CREATEUSER('X_' || i.MANV, '123', 'NHANVIEN');
    X_ADMIN.X_ADMIN_GRANTROLE('XR_' || i.VAITRO, 'X_' || i.MANV, 'NO');
  END LOOP;
END;
/

BEGIN
    X_ADMIN.X_ADMIN_CREATEUSER('X_NV0021', '123', 'NHANVIEN');
    X_ADMIN.X_ADMIN_GRANTROLE('XR_TRGDV', 'X_NV0021', 'NO');
END;
/

