-- Create role NVCB
CREATE ROLE XR_NVCB;
-- Create role GV
CREATE ROLE XR_GV;
GRANT XR_NVCB TO XR_GV;
-- Create role NVPDT
CREATE ROLE XR_NVPDT;
GRANT XR_NVCB TO XR_NVPDT;
-- Create role NVPKT
CREATE ROLE XR_NVPKT;
GRANT XR_NVCB TO XR_NVPKT;
-- Create role NVTCHC
CREATE ROLE XR_NVTCHC;
GRANT XR_NVCB TO XR_NVTCHC;
-- Create role NVCTSV
CREATE ROLE XR_NVCTSV;
GRANT XR_NVCB TO XR_NVCTSV;
-- Create role TRGDV
CREATE ROLE XR_TRGDV;
GRANT XR_NVCB TO XR_TRGDV;
-- Create role SINHVIEN
CREATE ROLE XR_SV;


COMMIT;