CREATE TABLE X_ADMIN.USER_ROLES(
    USERNAME VARCHAR2(10),
    ROLENAME VARCHAR2(10)
);


BEGIN
  FOR i IN (SELECT MASV FROM X_ADMIN.SINHVIEN) LOOP
    INSERT INTO X_ADMIN.USER_ROLES (USERNAME, ROLENAME) VALUES (i.MASV, 'XR_'|| 'SV');
  END LOOP;
END;
/
BEGIN
  FOR i IN (SELECT MANV, VAITRO FROM X_ADMIN.NHANVIEN) LOOP
    INSERT INTO X_ADMIN.USER_ROLES (USERNAME, ROLENAME) VALUES (i.MANV, 'XR_' || i.VAITRO);
  END LOOP;
END;
/

GRANT SELECT ON X_ADMIN.USER_ROLES TO PUBLIC;
COMMIT;

CREATE CONTEXT X_UNIVERSITY_CONTEXT USING SET_X_UNIVERSITY_CONTEXT;

CREATE OR REPLACE PROCEDURE SET_X_UNIVERSITY_CONTEXT
AS
    isSV INTEGER;
    isGV INTEGER;
    isNVCB INTEGER;
    isNVPDT INTEGER;
    isNVPKT INTEGER;
    isNVTCHC INTEGER;
    isNVCTSV INTEGER;
    isTRGDV INTEGER;
    userId VARCHAR(10);
BEGIN
    userId :=  SUBSTR(SYS_CONTEXT('USERENV','SESSION_USER'), INSTR(SYS_CONTEXT('USERENV','SESSION_USER'), '_') + 1);

    DBMS_SESSION.SET_CONTEXT('X_UNIVERSITY_CONTEXT', 'USER_NAME', userId);

    SELECT COUNT(*) INTO isSV FROM X_ADMIN.USER_ROLES WHERE ROLENAME = 'XR_SV' and username = userId;
    DBMS_SESSION.SET_CONTEXT('X_UNIVERSITY_CONTEXT', 'IS_SV', isSV);

    SELECT COUNT(*) INTO isGV FROM X_ADMIN.USER_ROLES WHERE ROLENAME = 'XR_GV' and username = userId;
    DBMS_SESSION.SET_CONTEXT('X_UNIVERSITY_CONTEXT', 'IS_GV', isGV);

    SELECT COUNT(*) INTO isNVCB FROM X_ADMIN.USER_ROLES WHERE ROLENAME = 'XR_NVCB' and username = userId;
    DBMS_SESSION.SET_CONTEXT('X_UNIVERSITY_CONTEXT', 'IS_NVCB', isNVCB);

    SELECT COUNT(*) INTO isNVPDT FROM X_ADMIN.USER_ROLES WHERE ROLENAME = 'XR_NVPDT' and username = userId;
    DBMS_SESSION.SET_CONTEXT('X_UNIVERSITY_CONTEXT', 'IS_NVPDT', isNVPDT);

    SELECT COUNT(*) INTO isNVPKT FROM X_ADMIN.USER_ROLES WHERE ROLENAME = 'XR_NVPKT' and username = userId;
    DBMS_SESSION.SET_CONTEXT('X_UNIVERSITY_CONTEXT', 'IS_NVPKT', isNVPKT);

    SELECT COUNT(*) INTO isNVTCHC FROM X_ADMIN.USER_ROLES WHERE ROLENAME = 'XR_NVTCHC' and username = userId;
    DBMS_SESSION.SET_CONTEXT('X_UNIVERSITY_CONTEXT', 'IS_NVTCHC', isNVTCHC);

    SELECT COUNT(*) INTO isNVCTSV FROM X_ADMIN.USER_ROLES WHERE ROLENAME = 'XR_NVCTSV' and username = userId;
    DBMS_SESSION.SET_CONTEXT('X_UNIVERSITY_CONTEXT', 'IS_NVCTSV', isNVCTSV);

    SELECT COUNT(*) INTO isTRGDV FROM X_ADMIN.USER_ROLES WHERE ROLENAME = 'XR_TRGDV' and username = userId;
    DBMS_SESSION.SET_CONTEXT('X_UNIVERSITY_CONTEXT', 'IS_TRGDV', isTRGDV);
END;
/

GRANT EXECUTE ON SYS.SET_X_UNIVERSITY_CONTEXT TO PUBLIC;

CREATE OR REPLACE TRIGGER SET_X_UNIVERSITY_CONTEXT_TRIGGER
  AFTER LOGON ON DATABASE
BEGIN
  SYS.SET_X_UNIVERSITY_CONTEXT;
END;
/


COMMIT;